// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-mN9vAaMavMcQekfR5hgly6VepZnoTNM',
    appId: '1:1018243657906:web:9bf3da1e99f81332c399ab',
    messagingSenderId: '1018243657906',
    projectId: 'project-uas-f3d36',
    authDomain: 'project-uas-f3d36.firebaseapp.com',
    storageBucket: 'project-uas-f3d36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAjyXeZMvk8QY5KIiZa2Sx9-JBOhCtskE',
    appId: '1:1018243657906:android:a32d678bc9030e7bc399ab',
    messagingSenderId: '1018243657906',
    projectId: 'project-uas-f3d36',
    storageBucket: 'project-uas-f3d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCprSJHz0flq2iV5AUBOcwrctG6AYozLig',
    appId: '1:1018243657906:ios:b66f557f5d01e6bec399ab',
    messagingSenderId: '1018243657906',
    projectId: 'project-uas-f3d36',
    storageBucket: 'project-uas-f3d36.appspot.com',
    iosClientId: '1018243657906-f2oa9lsjbq820aaeqnhrcgghbm86st2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCprSJHz0flq2iV5AUBOcwrctG6AYozLig',
    appId: '1:1018243657906:ios:b66f557f5d01e6bec399ab',
    messagingSenderId: '1018243657906',
    projectId: 'project-uas-f3d36',
    storageBucket: 'project-uas-f3d36.appspot.com',
    iosClientId: '1018243657906-f2oa9lsjbq820aaeqnhrcgghbm86st2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUas',
  );
}
